const result = {
    "status": "ok",
    "total_hits": 1902,
    "page": 1,
    "total_pages": 96,
    "page_size": 20,
    "articles": [
        {
            "title": "Accident in Tyrol: Four dead in an avalanche accident",
            "author": null,
            "published_date": "2022-02-04 15:01:29",
            "published_date_precision": "full",
            "link": "https://www.tellerreport.com/life/2022-02-04-accident-in-tyrol--four-dead-in-an-avalanche-accident.SyfCk65CF.html",
            "clean_url": "tellerreport.com",
            "excerpt": "Four people did not survive an avalanche on the Tyrolean-Swiss border on Friday. Another person is still missing. A German skier, on the other hand, could be rescued the day before.",
            "summary": "Four people did not survive an avalanche on the Tyrolean-Swiss border on Friday. Another person is still missing. A German skier, on the other hand, could be rescued the day before. Four people died in an avalanche on the Tyrolean-Swiss border on Friday. One person is still missing, as several Austrian media reported, citing the control center in Tyrol. Information on the identity and nationality of the victims was initially not available. Rescue helicopters from Austria and Switzerland were deployed at the scene of the accident.",
            "rights": "tellerreport.com",
            "rank": 38336,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://media1.faz.net/ppmedia/aktuell/gesellschaft/1435715462/1.7780333/facebook_teaser/in-einem-skigebiet-in.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.348092,
            "_id": "b95e4d0a5924e94e57a096cd6dd87e9f"
        },
        {
            "title": "After the Accident",
            "author": null,
            "published_date": "2022-02-04 00:48:00",
            "published_date_precision": "full",
            "link": "https://www.dvidshub.net/news/413962/after-accident",
            "clean_url": "dvidshub.net",
            "excerpt": "As the light of a new day slowly began to creep over the hills of Temecula, California, Staff Sgt. Johnathan Jones, an administration specialist working aboard Marine Corps Base Camp Pendleton, jolted…",
            "summary": "As the light of a new day slowly began to creep over the hills of Temecula, California, Staff Sgt. Johnathan Jones, an administration specialist working aboard Marine Corps Base Camp Pendleton, jolted out of bed half awake; his alarm ringing mercilessly in the background. With little regard to his surroundings, Staff Sgt. Jones frantically scurried and stumbled across his small Southern California suburban home. Going through a morning routine in five minutes to what usually takes 35, Jones refused to be late to work, again.",
            "rights": "dvidshub.net",
            "rank": 6974,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://d1ldvf68ux039x.cloudfront.net/thumbs/photos/1908/5713504/1000w_q95.jpg",
            "is_opinion": false,
            "twitter_account": "@dvidshub",
            "_score": 11.177254,
            "_id": "f38761adb2dbba0e0770db9d25197df9"
        },
        {
            "title": "Snowmobile Accident in Farmington",
            "author": null,
            "published_date": "2022-02-02 16:05:45",
            "published_date_precision": "full",
            "link": "https://www.einnews.com/pr_news/562149027/snowmobile-accident-in-farmington",
            "clean_url": "einnews.com",
            "excerpt": "CONTACT: CO Ronald B. Arsenault 603-744-5470 603-271-3361 February 2, 2022 Farmington, NH – On Tuesday, February 1, shortly before 9:30 a.m., New Hampshire Fish",
            "summary": "CONTACT: CO Ronald B. Arsenault 603-744-5470 603-271-3361 February 2, 2022 Farmington, NH – On Tuesday, February 1, shortly before 9:30 a.m., New Hampshire Fish and Game was notified that a snowmobile had crashed on Corridor 305. The rider was John Bartlett, 54, of Auburn, NH. Bartlett was riding with a friend and leading the way. After a long, straight, flat stretch in the trail, the track turns sharply to the left. Due to speed and watering of the eyes, Bartlett missed the corner and went approximately 40 feet into the woods and struck a tree and a rock.",
            "rights": null,
            "rank": 4959,
            "topic": "news",
            "country": "UA",
            "language": "en",
            "authors": [],
            "media": "https://i0.wp.com/nhfishgame.com/wp-content/uploads/2021/06/law-logo-edited.jpg?fit=400%2C400&ssl=1",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.819403,
            "_id": "db334f058c0dfe6edc60974a683c8f0d"
        },
        {
            "title": "Motorcyclist dies in accident",
            "author": "https://tribune.com.pk/author/1059",
            "published_date": "2022-01-31 06:44:06",
            "published_date_precision": "full",
            "link": "https://tribune.com.pk/story/2341246/motorcyclist-dies-in-accident",
            "clean_url": "tribune.com.pk",
            "excerpt": "Police arrested the driver and were investigating the matter further.",
            "summary": "Police arrested the driver and were investigating the matter further. LAHORE: A 35-year-old man died and his minor daughter sustained injuries after a speeding ambulance hit their motorcycle on Walton Road. The ambulance driver had reportedly lost control of his vehicle due to brake failure, and he hit the motorcyclist Waqas Tariq and his four-year-old daughter Ayat. The victims received serious injuries, said SP of Traffic Asif Siddique. They were shifted to a nearby hospital where Waqas Tariq died.",
            "rights": "tribune.com.pk",
            "rank": 4304,
            "topic": "news",
            "country": "PK",
            "language": "en",
            "authors": [ "https://tribune.com.pk/author/1059" ],
            "media": "https://i.tribune.com.pk/media/images/722726-motorcycles-1402957893/722726-motorcycles-1402957893.JPG",
            "is_opinion": false,
            "twitter_account": "@etribune",
            "_score": 10.663988,
            "_id": "5ca7e05db6c6e0fb1ea196f76b21b163"
        },
        {
            "title": "Accidents: February 2022",
            "author": "David Jack Kenny",
            "published_date": "2022-02-01 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.ainonline.com/aviation-news/business-aviation/2022-02-01/accidents-february-2022",
            "clean_url": "ainonline.com",
            "excerpt": "Preliminary and final accident reports, February 2022",
            "summary": "Nine Fatalities in Dominican Gulfstream Crash Gulfstream GIV-SP, Dec. 15, 2021, Santo Domingo, Las Americás International Airport, Dominican Republic - All nine on board were killed when the airplane went down during an attempted emergency diversion to the Santo Domingo--Las Americás International Airport shortly after departure from the La Isabela airport in Higuero. Initial accounts indicate that one of the two pilots reported an unspecified problem with the aircraft when requesting the diversion.",
            "rights": "ainonline.com",
            "rank": 16952,
            "topic": "business",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://www.ainonline.com/misc/favicon.ico",
            "is_opinion": false,
            "twitter_account": "@AINonline",
            "_score": 10.4451065,
            "_id": "7ceade991ca9edd29b73fa986f940d61"
        },
        {
            "title":" Six injured in accident",
            "author": "INP, https://www.brecorder.com/authors/77977/inp",
            "published_date": "2022-01-31 07:10:46",
            "published_date_precision": "timezone unknown",
            "link": "https://www.brecorder.com/news/40150967",
            "clean_url": "brecorder.com",
            "excerpt": "KARACHI: At least six persons sustained injuries on Sunday following a gas leakage blast at Ghazi Goth here. 'The...",
            "summary": "KARACHI: At least six persons sustained injuries on Sunday following a gas leakage blast at Ghazi Goth here. 'The blast was caused by gas leakage from a water tank in a house of Ghazi Goth in Sachal police jurisdiction,' police said. 'The explosion took place owing to pressure of gas during cleaning of a water tank,' according to police.'A man who entered in the water tank for cleaning ignited a match stick, which resulted in explosion,' police officials said. In another incident recently, a gas leakage blast took place inside a company located near Hub Chowki, injuring 10 people, rescue sources said.",
            "rights": "brecorder.com",
            "rank": 14720,
            "topic": "news",
            "country": "PK",
            "language": "en",
            "authors":[ "INP", "https://www.brecorder.com/authors/77977/inp"],
            "media": "https://i.brecorder.com/large/2022/01/61f7428f2e733.jpg",
            "is_opinion": false,
            "twitter_account": "@brecordernews",
            "_score": 10.443134,
            "_id": "f3fecd2d3e424e2810aa9e5f96a44c87"
        },
        {
            "title": "Snowmobile Accident in Farmington",
            "author": null,
            "published_date": "2022-02-02 16:05:45",
            "published_date_precision": "full",
            "link": "https://www.einpresswire.com/article/562160472/snowmobile-accident-in-farmington",
            "clean_url": "einpresswire.com",
            "excerpt": "CONTACT: CO Ronald B. Arsenault 603-744-5470 603-271-3361 February 2, 2022 Farmington, NH – On Tuesday, February 1, shortly before 9:30 a.m., New Hampshire Fish",
            "summary": "CONTACT: CO Ronald B. Arsenault 603-744-5470 603-271-3361 February 2, 2022 Farmington, NH – On Tuesday, February 1, shortly before 9:30 a.m., New Hampshire Fish and Game was notified that a snowmobile had crashed on Corridor 305. The rider was John Bartlett, 54, of Auburn, NH. Bartlett was riding with a friend and leading the way. After a long, straight, flat stretch in the trail, the track turns sharply to the left. Due to speed and watering of the eyes, Bartlett missed the corner and went approximately 40 feet into the woods and struck a tree and a rock.",
            "rights": "einpresswire.com",
            "rank": 16683,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://i0.wp.com/nhfishgame.com/wp-content/uploads/2021/06/law-logo-edited.jpg?fit=400%2C400&ssl=1",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.422894,
            "_id": "84fd0c29bcf983457950395532aa5f76"
        },
        {
            "title": "Youth killed in accident",
            "author": "Staff Reporter",
            "published_date": "2022-01-29 18:19:02",
            "published_date_precision": "full",
            "link": "https://www.thehindu.com/news/cities/Coimbatore/youth-killed-in-accident/article38346743.ece",
            "clean_url": "thehindu.com",
            "excerpt": "A youth was killed and six others were injured in a road accident at Chettipalayam in the outskirts of Coimbatore on Saturday. According to the police, Neil George (22), a first-year MBA student at a",
            "summary": "A youth was killed and six others were injured in a road accident at Chettipalayam in the outskirts of Coimbatore on Saturday. According to the police, Neil George (22), a first-year MBA student at a private college, was travelling in a car with six of his friends on Chettipalayam-Negamam road. The vehicle approached Periyakuili Pirivu near Chettipalayam around 4.45 p.m. when it lost control after seeing a truck approach in the opposite direction and the car turned turtle. Neil George died on the spot due to heavy bleeding injuries while his friends Brijesh, Sree, Varshini, Nancy, Vasanth and Michael escaped with injuries.",
            "rights": "Copyright 2022 The Hindu",
            "rank": 1162,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": ["Staff Reporter"],
            "media": "https://www.thehindu.com/static/theme/default/base/img/og-image.jpg",
            "is_opinion": false,
            "twitter_account": "Staff Reporter",
            "_score": 10.364814,
            "_id": "4a8d684c30de3668bc17d3a634a914d6"
        },
        {
            "title": "Kanpur Bus Accident",
            "author": null,
            "published_date": "2022-01-31 16:18:38",
            "published_date_precision": "full",
            "link": "https://www.latestly.com/socially/india/news/kanpur-bus-accident-inquiry-committee-formed-by-state-government-to-probe-bus-crash-latest-tweet-by-pti-news-3312742.html",
            "clean_url": "latestly.com",
            "excerpt": "The latest Tweet by PTI News states, 'Kanpur bus accident: Inquiry committee formed by state government to probe bus crash, local agencies also investigating matter to prevent such episodes in future:…",
            "summary": "Socially Team Latestly| Jan 31, 2022 09:48 PM IST Kanpur bus accident: Inquiry committee formed by state government to probe bus crash, local agencies also investigating matter to prevent such episodes in future: Divisional Commissioner Raj Shekhar— Press Trust of India (@PTI_News) January 31, 2022(SocialLY brings you all the latest breaking news, viral trends and information from social media world, including Twitter, Instagram and Youtube. The above post is embeded directly from the user's social media account and LatestLY Staff may not have modified or edited the content body.",
            "rights": "latestly.com",
            "rank": 40754,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [],
            "media": "https://st1.latestly.com/wp-content/uploads/2021/06/1-PTI-784x441.png",
            "is_opinion": false,
            "twitter_account": "@latestly",
            "_score": 10.261714,
            "_id": "883a86fbcaa6d681613061c88e0758e5"
        },
        {
            "title": "Accident on HWY 151 near Springville; second accident in under 18 hours",
            "author": "KCRG Staff",
            "published_date": "2022-02-01 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.kcrg.com/2022/02/01/accident-hwy-151-near-springville-second-accident-under-18-hours",
            "clean_url": "kcrg.com",
            "excerpt": "DOT images show emergency vehicles on scene by 1:10 pm on Tuesday, less than 18 hours after they were there Monday night.",
            "summary": "SPRINGVILLE, Iowa (KCRG) - At approximately 1:00 pm on Tuesday, a car accident occurred on Highway 151 at mile marker 43 near Springville - less than a day after another multivehicle accident occurred in the same spot.Emergency responders arrived on Tuesday's scene to discover a Lincoln passenger car was struck by a semi-tractor and trailer, in the southbound lanes of Highway 151.An investigation showed, that the passenger car was traveling north on Springville Rd and failed to yield at the crossover to the southbound semi-tractor and trailer.",
            "rights": "kcrg.com",
            "rank": 12629,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://gray-kcrg-prod.cdn.arcpublishing.com/resizer/wKpb3GaGYyK1mpamA5YtcY-AXQg=/980x0/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/6A35XWR3HFBYLGTMLREKYZ3LCI.jpg",
            "is_opinion": false,
            "twitter_account": "@KCRG",
            "_score": 10.201396,
            "_id": "2d124eaf442089dcb25a6c5059738f11"
        },
        {
            "title": "Worker trapped in construction accident",
            "author": null,
            "published_date": "2022-02-03 05:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://news.yahoo.com/worker-trapped-construction-accident-034702296.html",
            "clean_url": "yahoo.com",
            "excerpt": "Authorities say a construction worker became trapped at a work site in Lake County on Wednesday.",
            "summary": "The Hill A Georgia sheriff announced on Monday that he will offer $500,000 of his own money to anyone who has information regarding the case of Georgia teen Kendrick Johnson, who was found in a rolled-up gym mat in 2013, just days after closing the investigation into his death.Lowndes County Sheriff Ashley Paulk announced Thursday that Johnson's case would be closed and no charges would be filed with the release of a 16-page document detailing the...",
            "rights": "yahoo.com",
            "rank": 30,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://s.yimg.com/ny/api/res/1.2/iILcmQmaj800.BMAdt51AA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://s.yimg.com/hd/cp-video-transcode/production/f28d862d-1757-3b64-b70e-5eb1bb431897/2022-02-03/04-26-04/4fb280db-dcf8-5be7-8ab8-14d8b0ecd96d/stream_1280x720x0_v2_3_0.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.158561,
            "_id": "28db508d43201e82cdd0369e1605f39c"
        },
        {
            "title": "The Met's toxic subcultures are no accident",
            "author": "Paul Mason Is A New Statesman Contributing Writer",
            "published_date": "2022-02-02 14:35:24",
            "published_date_precision": "full",
            "link": "https://www.newstatesman.com/comment/2022/02/the-mets-toxic-subcultures-are-no-accident",
            "clean_url": "newstatesman.com",
            "excerpt": "Unless policing is publicly accountable, it will remain as racist and misogynistic as it was with the officers in Charing Cross.",
            "summary": "Photo by JUSTIN TALLIS/AFP via Getty Images A Metropolitan Police officer, known to his colleagues as 'the rapist', raped and murdered a young woman using his police ID for cover. When women took to the streets to protest this, officers from the force pinned some of them violently to the ground. Then, two Metropolitan Police officers were jailed for taking photographs of female murder victims and sharing them with a WhatsApp group of 41 colleagues. Now, in the latest sickening example of organised racism and misogyny, we have the Charing Cross revelations.",
            "rights": "newstatesman.com",
            "rank": 1990,
            "topic": "news",
            "country": "GB",
            "language": "en",
            "authors": ["Paul Mason Is A New Statesman Contributing Writer",
                    "The Author Of Postcapitalism.",
                    "More This Author",
                    "Paul Mason"
            ],
            "media": "https://www.newstatesman.com/wp-content/uploads/sites/2/2022/02/GettyImages-1231693042-1038x778.jpg",
            "is_opinion": false,
            "twitter_account": "@paulmasonnews",
            "_score": 10.126972,
            "_id": "74bfbaf8c18a774b74891eb0a9764545"
        },
        {
            "title": "Accidents reported across the state",
            "author": "KWCH Staff",
            "published_date": "2022-02-02 13:51:00",
            "published_date_precision": "full",
            "link": "https://www.kwch.com/2022/02/02/accidents-reported-across-state",
            "clean_url": "kwch.com",
            "excerpt": "Sedgwick County dispatch advises drivers to avoid highways.",
            "summary": "WICHITA, Kan. (KWCH) - With blowing snow creating hazardous road conditions, several accidents and road closures have been reported across the Wichita area and throughout the state. Sedgwick County dispatch advises drivers to avoid highways, where most of the accidents have taken place. Trooper Fleming handling an injury crash on I-70 in eastern Saline county.#SlowDown #KSwx ❄️ pic.twitter.com/ArbZ00d8CV — Trooper Ben (@TrooperBenKHP) February 2, 2022 Snow is affecting some parts of NWKS this morning with roads snowpacked and icy in spots.",
            "rights": "kwch.com",
            "rank": 17752,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://gray-kwch-prod.cdn.arcpublishing.com/resizer/Rnm0ld7QsuUg8xwtSTaUxcPkHmI=/980x0/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/53DWJLD3NJBCJOPE27VR4BQ6TI.png",
            "is_opinion": false,
            "twitter_account": "@KWCH12",
            "_score": 10.086117,
            "_id": "a213ef6ccf29e9a0f924f3d38e3ced4e",
        },
        {
            "title": "Ambala: Motorcyclist killed in accident",
            "author": "Var Follow_Widget_Data",
            "published_date": "2022-01-31 22:51:04",
            "published_date_precision": "full",
            "link": "https://indianexpress.com/article/cities/ambala-motorcyclist-killed-in-accident-7750529",
            "clean_url": "indianexpress.com",
            "excerpt": "🔴 Police registered a case on the complaint of a cousin of Raj Kumar's, who stated that Raj Kumar's bike entered the truck from below the truck.",
            "summary": "A motorcyclist identified as Raj Kumar, a resident of Alawalpur, died when his bike hit a truck parked on the roadside near village Dhakola on Saha-Shabad highway, early morning on Monday. Police registered a case on the complaint of a cousin of Raj Kumar's, who stated that Raj Kumar's bike entered the truck from below the truck. He was pulled out by passersby and taken to MM Medical College, where the doctors declared him dead. The police handed over his body to the family after postmortem. 📣 The Indian Express is now on Telegram.",
            "rights": "indianexpress.com",
            "rank": 1201,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors":[ "Var Follow_Widget_Data",
                    "Af_Article_Count",
                    "Ie_Mobile_Check",
                    "No",
                    "Ajax_Url",
                    "Https",
                    "Indianexpress.Com",
                    "Wp-Admin",
                    "Admin-Ajax.Php",
                    "Tracking_C"
            ],
            "media": "https://images.indianexpress.com/2022/02/ROAD-ACCIDENT.jpg",
            "is_opinion": false,
            "twitter_account": "@indianexpress",
            "_score": 10.076762,
            "_id": "e3d1eec8e4b5b7a1b2618f2a644542dd"
        },
        {
            "title": "Couple killed in road accident",
            "author": "Special Correspondent",
            "published_date": "2022-02-01 15:40:08",
            "published_date_precision": "full",
            "link": "https://www.thehindu.com/news/cities/Madurai/accident/article38360477.ece",
            "clean_url": "thehindu.com",
            "excerpt": "A couple died on the spot when the car in which they were travelling collided head on with a TNSTC bus coming on the opposite direction at Sithalangudi near Poovanthi in Sivaganga district on Tuesday.",
            "summary": "A couple died on the spot when the car in which they were travelling collided head on with a TNSTC bus coming on the opposite direction at Sithalangudi near Poovanthi in Sivaganga district on Tuesday.Veerakalai, 46, and his wife Kavitha, 41, of Maravamangalam near Kalayarkoil in Sivaganga district were returning to their home after dropping their daughter in Madurai Maatuthavani Bus Stand. As the car was approaching Sithalangudi, a bus, which was bound for Madurai, collided. In the impact, both died on the spot.",
            "rights": "Copyright 2022 The Hindu",
            "rank": 1162,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors":[ "Special Correspondent" ],
            "media": "https://www.thehindu.com/static/theme/default/base/img/og-image.jpg",
            "is_opinion": false,
            "twitter_account": "@The_Hindu",
            "_score": 10.0541525,
            "_id": "5c5692df3ee6cea4d2bcc0fb5f73947f"
        },
        {
            "title": "Woman dies in Haripur accident",
            "author": null,
            "published_date": "2022-02-03 01:00:00",
            "published_date_precision": "full",
            "link": "https://www.thenews.com.pk/print/930406-woman-dies-in-haripur-accident",
            "clean_url": "thenews.com.pk",
            "excerpt": "HARIPUR: A woman was killed while another passenger was injured when a pickup plunged into a roadside ravine in a remote Bait Gali village in Ghazi tehsil, police said here on...",
            "summary": "HARIPUR: A woman was killed while another passenger was injured when a pickup plunged into a roadside ravine in a remote Bait Gali village in Ghazi tehsil, police said here on Wednesday. Officials of the Nara Amazai Police Station quoted eyewitnesses as saying that a datsun pick carrying two passengers was on the way to Topi from Bait Gali village when the driver lost control over the wheels and the vehicle plunged into a gorge while negotiating a blind turn near Devi village. As a result, a woman later identified as Gul Rahban Bibi was killed on the spot while Siddiqu, a resident of Devi village, was injured.",
            "rights": "thenews.com.pk",
            "rank": 5444,
            "topic": "news",
            "country": "PK",
            "language": "en",
            "authors": [],
            "media": "https://www.thenews.com.pk/assets/front/img/no-img-fb.jpg",
            "is_opinion": false,
            "twitter_account": "@thenews_intl",
            "_score": 9.991166,
            "_id": "e5ddb4375e1c8cc3cc19973d9ca2b9c7"
        },
        {
            "title": "Snow causes flurry of accidents",
            "author": null,
            "published_date": "2022-02-01 02:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www2.ljworld.com/news/2007/feb/16/snow_causes_flurry_accidents",
            "clean_url": "ljworld.com",
            "excerpt": "Since the snow started falling this afternoon, Lawrence police have responded to 19 noninjury accidents, police spokeswoman Kim Murphree said.The calls have been widespread across the city, including…",
            "summary": "News Feb 16, 2007 - 5:10pm Since the snow started falling this afternoon, Lawrence police have responded to 19 noninjury accidents, police spokeswoman Kim Murphree said. The calls have been widespread across the city, including three on Iowa Street, two on Wakarusa Drive and two on Louisiana Street. No injuries have been reported, Murphree said. Emergency dispatchers have also reported several slide-offs in the county this afternoon. The National Weather Service has issued a Snow and Blowing Snow Advisory for Lawrence and Douglas County, and forecasters have predicted a total nighttime snow and sleet accumulation of 1 to 2 inches.",
            "rights": "ljworld.com",
            "rank": 12332,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://s3.amazonaws.com/ogden_images/www.ljworld.com/images/2018/06/05102645/fb.jpg",
            "is_opinion": false,
            "twitter_account": "@ljworld",
            "_score": 9.988833,
            "_id": "792b58e6adc99a251b823a4d2cb1a873"
        },
        {
            "title": "Kuwaiti perishes in accident",
            "author": null,
            "published_date": "2022-01-30 01:30:00",
            "published_date_precision": "timezone unknown",
            "link": "http://www.arabtimesonline.com/news/kuwaiti-perishes-in-accident",
            "clean_url": "arabtimesonline.com",
            "excerpt": "KUWAIT CITY, Jan 29: The Public Relations and Media Department of the Public Fire Services Directorate reported a Kuwaiti died on the King Fahd Road this morning following a collision between a…",
            "summary": "KUWAIT CITY, Jan 29: The Public Relations and Media Department of the Public Fire Services Directorate reported a Kuwaiti died on the King Fahd Road this morning following a collision between a transport truck and a four-wheel drive, reports Al-Rai daily. The daily added, upon collision the four-wheel drive ran out control, overturned and came to rest against a tree on the side of the road. The Arab man who was in the other vehicle was seriously injured and has been rushed to a hospital. The department said firemen from the Mina Abdullah Firefighting Center dealt with the accident.",
            "rights": null,
            "rank": 46244,
            "topic": "news",
            "country": "KW",
            "language": "en",
            "authors": [],
            "media": "http://www.arabtimesonline.com/news/file/2022/01/accident4-1.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.973231,
            "_id": "15dda1059ee3ecf372fad912b49225f1"
        },
        {
            "title": "TransCanada an accident zone",
            "author": "Westman Rcmp",
            "published_date": "2022-01-31 21:55:18",
            "published_date_precision": "full",
            "link": "https://www.empireadvance.ca/local-news/transcanada-an-accident-zone-highway-travel-not-recommended-5013015",
            "clean_url": "empireadvance.ca",
            "excerpt": "January 31 RCMP are expecting the TransCanada to close due to icy conditions.",
            "summary": "January 31st, 2022 Westman Detachment has been responding to multiple vehicle accidents on #1 Highway due to slippery road conditions.  While responding to these accidents, several more vehicles also slid into the ditch including several highway tractor/trailer units.  Manitoba Department of Highways has been actively attempting to alleviate the slippery road conditions, and at this time it's strongly recommended to avoid travel unless absolutely necessary.  Hockey is not in our necessary travel category, nor is curling, Glee Club, voice lessons, Chess Club, or square dancing.",
            "rights": "empireadvance.ca",
            "rank": 812101,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [ "Westman Rcmp" ],
            "media": "https://www.vmcdn.ca/f/files/virdenempireadvance/images/police/highwya.jpg;w=1024;h=742;mode=crop",
            "is_opinion": false,
            "twitter_account": "@",
            "_score": 9.964573,
            "_id": "174e623e3a6d6e63fb9d0eb312ec1aa3"
        },
        {
            "title": "Accident closes M6 southbound",
            "author": "Paul Jenkins",
            "published_date": "2022-02-04 16:14:12",
            "published_date_precision": "full",
            "link": "https://www.expressandstar.com/news/2022/02/04/accident-closes-m6-southbound",
            "clean_url": "expressandstar.com",
            "excerpt": "Commuters face Friday afternoon misery on the motorways as the M6 is currently blocked southbound between junction six for Birmingham and the A38 and junction five for Sutton Coldfield.",
            "summary": "Accident on M6Police, ambulance and highways officers are in attendance and long delays on surrounding routes are expected.",
            "rights": "expressandstar.com",
            "rank": 9242,
            "topic": "news",
            "country": "GB",
            "language": "en",
            "authors": [ "Paul Jenkins" ],
            "media": "https://www.expressandstar.com/resizer/dmewWTywCS3I4kodguS07IVCyUA=/1200x0/cloudfront-us-east-1.images.arcpublishing.com/mna/NYQ7NP3QFVCF7B77DMNTXPIQEQ.jpg",
            "is_opinion": false,
            "twitter_account": "expressandstar",
            "_score": 9.940386,
            "_id": "50ec4897144536b2399b763e8e76cb2f"
        }
    ],
    "user_input":{
        "q": "accident",
        "search_in": [ "title_en" ],
        "lang": [ "en" ],
    "not_lang": null,
    "countries": null,
    "not_countries": null,
    "from": "2022-01-28 18:03:37",
    "to": null,
    "ranked_only": "True",
    "from_rank": null,
    "to_rank": null,
    "sort_by": "relevancy",
    "page": 1,
    "size": 20,
    "sources": null,
    "not_sources":[ "youtube.com","google.com","reddit.com","9gag.com" ],
    "topic": null,
    "published_date_precision": null
    }
}

function getnews(req, res){
    res.status(200).json(result);
/*     res.status(401).json({ message: `Members delete id` });
    res.status(404).json({ message: `Members delete id` }); */
   }

module.exports = getnews;